networks:
  app-network:
    external: true  # Dùng network đã tạo bởi docker-compose.yml

services:
  frontend:
    build: 
      context: ./frontend
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL:-http://localhost:8090}
    container_name: frontend
    ports:
      - "80:5173"
    networks:
      - app-network
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL:-http://localhost:8090}
    restart: always
